const reasons = [
    "You always know how to make me smile.",
    "Your laugh is the sweetest sound in the world.",
    "You make even the smallest moments feel special.",
    "I love the way your eyes light up when you're happy.",
    "You believe in me even when I doubt myself.",
    "You give the warmest, most comforting hugs.",
    "You’re my biggest cheerleader in everything I do.",
    "I love how caring and thoughtful you are.",
    "You always support me no matter what.",
    "Your kindness makes the world a better place.",
    "You make me feel at home no matter where I am.",
    "I love how you challenge me to be a better person.",
    "You listen to me even when I ramble about nonsense.",
    "You’re the most beautiful person inside and out.",
    "Your touch is my favorite feeling in the world.",
    "You’re always there when I need you the most.",
    "I love the way you hold my hand.",
    "You inspire me with your strength and resilience.",
    "I love waking up and knowing you’re in my life.",
    "Your heart is pure and full of love.",
    "You always see the best in me.",
    "I love how passionate you are about the things you love.",
    "You know how to make me laugh even on my worst days.",
    "I love how you say my name.",
    "You make even the most ordinary days feel special.",
    "You always remember the little things.",
    "I love how we can talk for hours and never run out of things to say.",
    "You give me butterflies every single day.",
    "You make my life brighter just by being in it.",
    "You’re my favorite person to do nothing with.",
    "I love how you look at me with so much love.",
    "Your voice is the sweetest melody to my ears.",
    "You make me feel like the luckiest person alive.",
    "I love how you take care of me.",
    "You always know the right thing to say.",
    "I love your sense of adventure and excitement for life.",
    "You make even the simplest things fun.",
    "You are the reason I believe in love.",
    "I love how safe and loved you make me feel.",
    "Your kisses are my favorite thing in the world.",
    "You’re my best friend and my soulmate.",
    "I love how we can be silly together.",
    "You’re always patient with me.",
    "I love how you encourage me to chase my dreams.",
    "You make my heart skip a beat every time I see you.",
    "You are the most amazing person I’ve ever met.",
    "I love how you support my crazy ideas.",
    "You always know how to lift my spirits.",
    "You make me want to be a better person.",
    "I love the way you love me.",
    "You are my home no matter where we are.",
    "You bring so much happiness into my life.",
    "I love how we can be ourselves around each other.",
    "You are my dream come true.",
    "I love how you make me feel understood.",
    "You’re the best thing that’s ever happened to me.",
    "You complete me in every way.",
    "I love that you accept me for who I am.",
    "You make my heart feel full.",
    "You are my forever and always.",
    "I love every little thing about you.",
    "You make me fall in love with you all over again every day.",
    "You are the best part of my life.",
    "I love how you bring out the best in me.",
    "You are the love of my life.",
    "Every moment with you is precious.",
    "You are the most amazing gift life has given me.",
    "I love how you make me feel special.",
    "You’re my person, my love, my everything.",
    "I can’t wait to spend forever with you.",
    // Add more reasons here to reach 365
  ];
  
  export default reasons;
  